// This file is generated by UTPM (https://github.com/Thumuss/utpm)
#import "templates/apa-utils.typ": apa_bibliography, apa_summary, apa_figure, apa_content_body, apa_itemize, apa_unmarked-list
#import "templates/common.typ": common_content_body, common_flipped_page
#import "templates/cover.typ": inf_make_cover
#import "templates/constants.typ": spacing_double
